<x-app-layout>
    <x-slot name="header"><div><p class="text-sm font-bold uppercase text-[#9f7957]">Court calendar</p><h2 class="mt-2 text-3xl font-extrabold text-[#030203]">Edit Hearing</h2></div></x-slot>
    <div class="bg-[#eef0ec] py-8"><div class="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8">
        @if ($errors->any())<div class="mb-6 border border-red-200 bg-red-50 p-4 text-sm text-red-800">{{ $errors->first() }}</div>@endif
        <form method="POST" action="{{ route('hearings.update', $hearing->id) }}" class="bg-white p-6 shadow-sm">
            @csrf @method('PUT')
            <div class="grid gap-5 sm:grid-cols-2">
                <div class="sm:col-span-2"><label class="mb-2 block text-sm font-bold uppercase text-[#554b45]">Case / Client / Lawyer</label><select name="case_id" required class="w-full border-[#c1c1bd] bg-white text-[#030203] focus:border-[#9f7957] focus:ring-[#9f7957]">@foreach($cases as $c)<option value="{{ $c->id }}" @selected(old('case_id', $hearing->case_id) == $c->id)>{{ $c->case_number }} - {{ $c->case_title }} @if($c->client) / {{ $c->client->full_name }} @endif @if($c->assignedLawyer) / {{ $c->assignedLawyer->display_name }} @endif</option>@endforeach</select></div>
                <div><label class="mb-2 block text-sm font-bold uppercase text-[#554b45]">Date</label><input type="date" name="hearing_date" value="{{ old('hearing_date', $hearing->hearing_date) }}" min="1000-01-01" max="9999-12-31" class="w-full border-[#c1c1bd] bg-white text-[#030203] focus:border-[#9f7957] focus:ring-[#9f7957]"></div>
                <div><label class="mb-2 block text-sm font-bold uppercase text-[#554b45]">Time</label><input type="time" name="hearing_time" value="{{ old('hearing_time', $hearing->hearing_time) }}" class="w-full border-[#c1c1bd] bg-white text-[#030203] focus:border-[#9f7957] focus:ring-[#9f7957]"></div>
                <div><label class="mb-2 block text-sm font-bold uppercase text-[#554b45]">Venue</label><input type="text" name="court_venue" value="{{ old('court_venue', $hearing->court_venue) }}" class="w-full border-[#c1c1bd] bg-white text-[#030203] focus:border-[#9f7957] focus:ring-[#9f7957]"></div>
                <div><label class="mb-2 block text-sm font-bold uppercase text-[#554b45]">Branch</label><select name="court_branch" class="w-full border-[#c1c1bd] bg-white text-[#030203] focus:border-[#9f7957] focus:ring-[#9f7957]">@php($branches = ['RTC Branch 6 - Tacloban City, Leyte','RTC Branch 7 - Tacloban City, Leyte','RTC Branch 8 - Tacloban City, Leyte','RTC Branch 9 - Tacloban City, Leyte','RTC Branch 10 - Abuyog, Leyte','RTC Branch 11 - Calubian, Leyte','RTC Branch 12 - Ormoc City, Leyte','RTC Branch 13 - Carigara, Leyte','RTC Branch 14 - Baybay City, Leyte','RTC Branch 15 - Burauen, Leyte','RTC Branch 17 - Palompon, Leyte','RTC Branch 18 - Hilongos, Leyte','RTC Branch 34 - Tacloban City, Leyte','RTC Branch 35 - Ormoc City, Leyte','RTC Branch 36 - Carigara, Leyte','RTC Branch 43 - Tacloban City, Leyte','RTC Branch 44 - Tacloban City, Leyte'])@php($selectedBranch = old('court_branch', $hearing->court_branch))<option value="">Select branch</option>@if($selectedBranch && ! in_array($selectedBranch, $branches, true))<option value="{{ $selectedBranch }}" selected>{{ $selectedBranch }}</option>@endif @foreach($branches as $branch)<option value="{{ $branch }}" @selected($selectedBranch === $branch)>{{ $branch }}</option>@endforeach</select></div>
                <div><label class="mb-2 block text-sm font-bold uppercase text-[#554b45]">Judge</label><input type="text" name="judge_name" value="{{ old('judge_name', $hearing->judge_name) }}" class="w-full border-[#c1c1bd] bg-white text-[#030203] focus:border-[#9f7957] focus:ring-[#9f7957]"></div>
                <div><label class="mb-2 block text-sm font-bold uppercase text-[#554b45]">Jurisdiction</label><select name="court_jurisdiction" class="w-full border-[#c1c1bd] bg-white text-[#030203] focus:border-[#9f7957] focus:ring-[#9f7957]">@php($jurisdictions = ['Civil','Criminal','Family','Labor','Administrative','Commercial','Tax','Environmental','Election','Cybercrime','Small Claims','Land/Property','Probate','Corporate','Other'])@php($selectedJurisdiction = old('court_jurisdiction', $hearing->court_jurisdiction))<option value="">Select jurisdiction</option>@if($selectedJurisdiction && ! in_array($selectedJurisdiction, $jurisdictions, true))<option value="{{ $selectedJurisdiction }}" selected>{{ $selectedJurisdiction }}</option>@endif @foreach($jurisdictions as $jurisdiction)<option value="{{ $jurisdiction }}" @selected($selectedJurisdiction === $jurisdiction)>{{ $jurisdiction }}</option>@endforeach</select></div>
                <div><label class="mb-2 block text-sm font-bold uppercase text-[#554b45]">Status</label><select name="hearing_status" class="w-full border-[#c1c1bd] bg-white text-[#030203] focus:border-[#9f7957] focus:ring-[#9f7957]">@foreach(['Scheduled','Completed','Postponed','Cancelled'] as $status)<option value="{{ $status }}" @selected(old('hearing_status', $hearing->hearing_status) === $status)>{{ $status }}</option>@endforeach</select></div>
                <div class="sm:col-span-2"><label class="mb-2 block text-sm font-bold uppercase text-[#554b45]">Purpose</label><textarea name="hearing_purpose" rows="4" class="w-full border-[#c1c1bd] bg-white text-[#030203] focus:border-[#9f7957] focus:ring-[#9f7957]">{{ old('hearing_purpose', $hearing->hearing_purpose) }}</textarea></div>
            </div>
            <div class="mt-6 flex items-center justify-between border-t border-[#e3e3df] pt-5"><a href="{{ route('hearings.index') }}" class="text-sm font-bold text-[#554b45] hover:text-[#030203]">Cancel</a><button class="bg-[#030203] px-6 py-3 text-sm font-bold text-white transition hover:bg-[#554b45]">Save hearing</button></div>
        </form>
    </div></div>
</x-app-layout>
